### ISSUE TITLE
Values aren't updated

### ISSUE THREAD

**Issue by n1kko777** [DieTime/react-native-date-picker#4]
Values aren't updated when navigate from any screen to screen with DatePicker component. To fix it, add `setTimeout` to useEffect.

Code fragment:
`
  useEffect(() => {
    setTimeout(() => {
      scrollRef.current.scrollTo({
        y: dHeight * (value - digits[0]),
        animated: true,
      });
    }, 100);
  }, [dHeight, digits, value]);
`

This is due to the fact that in the first rendering, the component has empty data.

**Comment by DieTime** [comment]
Hi, thanks for contributing to the development of the component. I will try to understand and fix this problem in the near future.
